### ISSUE TITLE
ConcatSource.js:42 failing with Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by dryhurst** [webpack/webpack-sources#103]
I'm not sure how to report this since I don't know if this is a bug or just that I am not understanding how to use webpack 5

I am trying to follow the nextjs webpack5 module-federation example here: https://github.com/module-federation/module-federation-examples/tree/master/nextjs

I am incorporating this into my own project, so i am using just the next.config.js file from that example and some things from the package.json

when i try to run yarn dev i get the below output

if i change  

`source += typeof child === "string" ? child : child.source(); 
`
to

` source += typeof child === "string" ? child : null;
`
im able to run the application but i have no idea what the repercussions of that change will be since i have no idea what this code does. 

```
❯ yarn dev
yarn run v1.22.10
$ run-p api-mock next
$ node api-mock.js
$ next --port 3002
Processed 13 unique mocks.
Processed 0 unique presets.
Mock API listening on port 9500
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
ready - started server on http://localhost:3002
(node:3395) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/jdryhurs/work/skyline-federation/next1/node_modules/webpack-sources/lib/ConcatSource.js:42
                        source += typeof child === "string" ? child : child.source();
                                                                            ^

TypeError: Cannot read property 'source' of undefined
    at ConcatSource.source (/Users/jdryhurs/work/skyline-federation/next1/node_modules/webpack-sources/lib/ConcatSource.js:42:56)
    at getContent (/Users/jdryhurs/work/skyline-federation/next1/node_modules/webpack/lib/Compiler.js:629:39)
    at processMissingFile (/Users/jdryhurs/work/skyline-federation/next1/node_modules/webpack/lib/Compiler.js:745:24)
    at /Users/jdryhurs/work/skyline-federation/next1/node_modules/webpack/lib/Compiler.js:785:10
    at callback (/Users/jdryhurs/work/skyline-federation/next1/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (node:fs:199:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "next" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alexander-akait** [comment]
Can you provide how we can reproduce it?

**Comment by drphelps** [comment]
This is the result of a misconfigured/incompatible plugin. There's a fork [here](https://github.com/noreiller/nextjs-mf/tree/fix-merge-runtime) that more or less fixes the issue.
