### ISSUE TITLE
Error: "." is not in the SourceMap. still in 1.4.1

### ISSUE THREAD

**Issue by aaronjensen** [webpack/webpack-sources#65]
Similar to #55, but not fixed for me in 1.4.1, I get this when building:

```
$ NODE_ENV=production wp
Error: "." is not in the SourceMap.
    at BasicSourceMapConsumer.SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/user/Source/project/client/node_modules/terser-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:753:13)
    at /Users/user/Source/project/client/node_modules/terser-webpack-plugin/node_modules/webpack-sources/lib/applySourceMap.js:88:47
    at SourceNode_walk [as walk] (/Users/user/Source/project/client/node_modules/terser-webpack-plugin/node_modules/source-map/lib/source-node.js:230:9)
    at SourceNode_walk [as walk] (/Users/user/Source/project/client/node_modules/terser-webpack-plugin/node_modules/source-map/lib/source-node.js:226:13)
    at applySourceMap (/Users/user/Source/project/client/node_modules/terser-webpack-plugin/node_modules/webpack-sources/lib/applySourceMap.js:58:13)
    at SourceMapSource.node (/Users/user/Source/project/client/node_modules/terser-webpack-plugin/node_modules/webpack-sources/lib/SourceMapSource.js:36:11)
    at SourceMapSource.proto.sourceAndMap (/Users/user/Source/project/client/node_modules/terser-webpack-plugin/node_modules/webpack-sources/lib/SourceAndMapMixin.js:29:18)
    at getTaskForFile (/Users/user/Source/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:64:30)
    at files.forEach (/Users/user/Source/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:200:20)
    at Array.forEach (<anonymous>)
    at compilation.hooks.afterOptimizeChunkAssets.tap (/Users/user/Source/project/node_modules/webpack/lib/SourceMapDevToolPlugin.js:177:12)
    at SyncHook.eval [as call] (eval at create (/Users/user/Source/project/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/Users/user/Source/project/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/user/Source/project/node_modules/webpack/lib/Compilation.js:1385:42)
    at _promise1.then._result1 (eval at create (/Users/user/Source/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
```

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by aaronjensen** [comment]
> Please create minimum reproducible test repo

I'll work on it

**Comment by sokra** [comment]
Could you check if you are not accidentically using the 1.4.0 version? 

`client/node_modules/terser-webpack-plugin/node_modules/webpack-sources/package.json`

**Comment by aaronjensen** [comment]
> Could you check if you are not accidentically using the 1.4.0 version?

Yep, it looks like that was it. I cleared the old versions out of my yarn.lock and rebuilt and it worked fine. Thanks!
